;;;; openssl.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         foreign
         ports
         srfi-13
         srfi-18
         tcp
         (only srfi-13 string-join)
         (only data-structures ->string)
         (only files make-pathname)))
(##sys#register-compiled-module
  'libressl
  (list)
  '((ssl-connect . openssl#ssl-connect)
    (ssl-connect* . openssl#ssl-connect*)
    (ssl-make-client-context . openssl#ssl-make-client-context)
    (ssl-make-client-context* . openssl#ssl-make-client-context*)
    (ssl-client-context? . openssl#ssl-client-context?)
    (ssl-listen . openssl#ssl-listen)
    (ssl-listen* . openssl#ssl-listen*)
    (ssl-close . openssl#ssl-close)
    (ssl-port? . openssl#ssl-port?)
    (ssl-port->tcp-port . openssl#ssl-port->tcp-port)
    (ssl-listener? . openssl#ssl-listener?)
    (ssl-listener? . openssl#ssl-listener?)
    (ssl-listener-port . openssl#ssl-listener-port)
    (ssl-listener-fileno . openssl#ssl-listener-fileno)
    (ssl-accept-ready? . openssl#ssl-accept-ready?)
    (ssl-accept . openssl#ssl-accept)
    (ssl-handshake-timeout . openssl#ssl-handshake-timeout)
    (ssl-shutdown-timeout . openssl#ssl-shutdown-timeout)
    (ssl-set-cipher-list! . openssl#ssl-set-cipher-list!)
    (ssl-load-certificate-chain! . openssl#ssl-load-certificate-chain!)
    (ssl-load-private-key! . openssl#ssl-load-private-key!)
    (ssl-set-verify! . openssl#ssl-set-verify!)
    (ssl-load-verify-root-certificates!
      .
      openssl#ssl-load-verify-root-certificates!)
    (ssl-load-suggested-certificate-authorities!
      .
      openssl#ssl-load-suggested-certificate-authorities!)
    (ssl-peer-verified? . openssl#ssl-peer-verified?)
    (ssl-peer-subject-name . openssl#ssl-peer-subject-name)
    (ssl-peer-issuer-name . openssl#ssl-peer-issuer-name)
    (ssl-default-certificate-authority-directory
      .
      openssl#ssl-default-certificate-authority-directory)
    (ssl-make-i/o-ports . openssl#ssl-make-i/o-ports)
    (net-unwrap-tcp-ports . openssl#net-unwrap-tcp-ports))
  (list)
  (list))

;; END OF FILE
